Repository NucleoidMC/plasmid, pull requests merged in 2021-01, with the labels that each got.

#101 Use game IDs where possible for messages
  src/main/java/xyz/nucleoid/plasmid/command/GameCommand.java
  src/main/java/xyz/nucleoid/plasmid/command/argument/GameConfigArgument.java
  src/main/java/xyz/nucleoid/plasmid/game/ConfiguredGame.java
  src/main/java/xyz/nucleoid/plasmid/game/ManagedGameSpace.java
  src/main/java/xyz/nucleoid/plasmid/game/channel/on_demand/OnDemandGame.java
  src/main/java/xyz/nucleoid/plasmid/game/channel/oneshot/OneshotChannelBackend.java
  src/main/java/xyz/nucleoid/plasmid/game/channel/oneshot/OneshotChannelSystem.java
Labels: bug

#108 Start work on events for use by other mods
  src/main/java/xyz/nucleoid/plasmid/Plasmid.java
  src/main/java/xyz/nucleoid/plasmid/event/GameEvents.java
  src/main/java/xyz/nucleoid/plasmid/game/ConfiguredGame.java
  src/main/java/xyz/nucleoid/plasmid/game/GameOpenProcedure.java
  src/main/java/xyz/nucleoid/plasmid/game/ManagedGameSpace.java
  src/main/java/xyz/nucleoid/plasmid/game/channel/on_demand/OnDemandGame.java
  src/main/java/xyz/nucleoid/plasmid/game/channel/oneshot/OneshotChannelSystem.java
Labels: feature

#61 Networking documentation/specification
  doc/network.md
Labels: documentation, feature

#113 Support custom properties in game config
  src/main/java/xyz/nucleoid/plasmid/game/ConfiguredGame.java
Labels: feature
