Repository NucleoidMC/plasmid, pull requests merged in 2021-03, with the labels that each got.

#69 Remove worldgen
  src/main/java/xyz/nucleoid/plasmid/game/gen/GenHelper.java
  src/main/java/xyz/nucleoid/plasmid/game/gen/MapGen.java
  src/main/java/xyz/nucleoid/plasmid/game/gen/README.md
  src/main/java/xyz/nucleoid/plasmid/game/gen/feature/CactusGen.java
  src/main/java/xyz/nucleoid/plasmid/game/gen/feature/DiskGen.java
  src/main/java/xyz/nucleoid/plasmid/game/gen/feature/GrassGen.java
  src/main/java/xyz/nucleoid/plasmid/game/gen/feature/ShrubGen.java
  src/main/java/xyz/nucleoid/plasmid/game/gen/feature/tree/AspenTreeGen.java
  src/main/java/xyz/nucleoid/plasmid/game/gen/feature/tree/DeadTreeGen.java
  src/main/java/xyz/nucleoid/plasmid/game/gen/feature/tree/PoplarTreeGen.java
  src/main/java/xyz/nucleoid/plasmid/game/gen/feature/tree/SwampTreeGen.java
Labels: breaking change

#118 Pass ServerPlayerEntity instead of PlayerEntity to the drop item listener
  src/main/java/xyz/nucleoid/plasmid/game/event/DropItemListener.java
  src/main/java/xyz/nucleoid/plasmid/mixin/game/event/PlayerEntityMixin.java
  src/main/java/xyz/nucleoid/plasmid/mixin/game/event/ScreenHandlerMixin.java
Labels: breaking change, bug

#120 Add additional game close reasons
  src/main/java/xyz/nucleoid/plasmid/Plasmid.java
  src/main/java/xyz/nucleoid/plasmid/game/GameCloseReason.java
  src/main/java/xyz/nucleoid/plasmid/game/ManagedGameSpace.java
Labels: breaking change, documentation, feature

#127 Pass the explosion instead of its affected blocks to the explosion listener
  src/main/java/xyz/nucleoid/plasmid/game/event/ExplosionListener.java
  src/main/java/xyz/nucleoid/plasmid/mixin/game/event/ExplosionMixin.java
Labels: breaking change, feature

#125 Pass the reason to the game close listener
  src/main/java/xyz/nucleoid/plasmid/game/GameCloseReason.java
  src/main/java/xyz/nucleoid/plasmid/game/ManagedGameSpace.java
  src/main/java/xyz/nucleoid/plasmid/game/event/GameCloseListener.java
  src/main/java/xyz/nucleoid/plasmid/widget/GlobalWidgets.java
Labels: breaking change, feature

#132 Fix the explosion listener event type lambda method not specifying the correct parameters
  src/main/java/xyz/nucleoid/plasmid/game/event/ExplosionListener.java
Labels: bug
